FROM simplaex/linux-dev:ubuntu-16.04

RUN curl https://storage.googleapis.com/golang/go1.9.4.linux-amd64.tar.gz -o /tmp/go1.9.4.tar.gz; \
    cd /opt; \
    tar xfz /tmp/go1.9.4.tar.gz; \
    rm /tmp/go1.9.4.tar.gz

ENV PATH="/opt/go/bin:${PATH}"

