FROM simplaex/linux-dev:ubuntu-18.04

RUN curl https://storage.googleapis.com/golang/go1.10.1.linux-amd64.tar.gz -o /tmp/go1.10.tar.gz; \
    cd /opt; \
    tar xfz /tmp/go1.10.tar.gz; \
    rm /tmp/go1.10.tar.gz

ENV PATH="/opt/go/bin:${PATH}"

